### ISSUE TITLE
Migrate to Astro

### ISSUE THREAD

**Issue by cyrus01337** [haotian2006/MyDocs#2]
Can I do this?

It'll involve using Node and a number of other tools from my [Astro boilerplate project](https://github.com/cyrus01337/astro-app-boilerplate) that will allow the site to utilise Markdown as page content, which I've achieved before in my personal site ([source](https://github.com/cyrus01337/cyrus01337.co.uk/tree/main/src/content), [preview](https://cyrus01337.co.uk/blogs/why-i-quit-social-media)).

This would involve a total restructure and having to manually style this, though I'm willing to do the heavy lifting in that regard.

**Comment by cyrus01337** [comment]
Note that the reason why I'm asking is because I'm not sure how far you're willing to allow me to go, so I'd rather not abuse the permission you've given me right off the bat.

**Comment by haotian2006** [comment]
sure its fine. also fyi you can send me a dm on discord

**Comment by cyrus01337** [comment]
I quit Discord yesterday so no can do.

**Comment by haotian2006** [comment]
alr
