### ISSUE TITLE
Migrate developer tags

### ISSUE THREAD

**Issue by cyrus01337** [haotian2006/MyDocs#6]
Tracking issue.

I've a bunch of developer tags [here](https://github.com/cyrus01337/tags) that I've wanted here rather than in plaintext on a random repo, as web interfaces tend to look nicer.

**Comment by haotian2006** [comment]
Created a tags page for people to navigate tags more easily (WIP). I am wondering If we should add an author option that will automatically attach the pfp and link the github ACC of the author

**Comment by haotian2006** [comment]
I've added an author field and here's how it looks

![image](https://github.com/user-attachments/assets/75ca4829-c822-46e3-932d-ca65e511f098)
![image](https://github.com/user-attachments/assets/90563f93-f5f2-483e-89c3-90745d2b7f0e)

**Comment by cyrus01337** [comment]
Wow, great work on this!

Author option is great, loved the idea. The by line has a lot of surround space, however, I'm happy to correct this.

On the topic of authoring - how should we handle those that do not have Github accounts? I was thinking of ensuring a Github account is a prerequisite, though I wonder how complex setting this up to work with Discord as well could be.

**Comment by cyrus01337** [comment]
Also side note, it's best to setup branches and PRs so I can provide better feedback rather than vaguely outlining what I'm referring to in issues.

Just thought I'd let you know, if it's not too much a hassle. :P

**Comment by cyrus01337** [comment]
Thanks @haotian2006 for 8121c82b6867efbb92886c085d3b0a7046838c5b! :revolving_hearts:
